export default {
    FILTER: {
        SHOW_ALL: "SHOW_ALL",
        SHOW_ACTIVE: "SHOW_ACTIVE",
        SHOW_COMPLETED: "SHOW_COMPLETED"
    },
    ADD_TODO:"ADD_TODO",
    REMOVE_TODO:"REMOVE_TODO",
    TOGGLE_TODO:"TOGGLE_TODO",
    SET_VISIBILITY_FILTER:"SET_VISIBILITY_FILTER"
};
